[build]
  publish = "."
  functions = "netlify/functions"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Cache-Control = "no-cache"

# Disable Cloudflare email obfuscation permanently
[build.environment]
  NETLIFY_EMAILS_SECRET = ""
