[build]
  publish = "."
  functions = "netlify/functions"
 
[build.processing]
  skip_processing = false
 
[build.processing.html]
  pretty_urls = true
 
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Content-Type-Options = "nosniff"
 
